# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
# permalink: pretty
permalink: /:categories/:year/:title:output_ext

# Setup
title: tristanlukens
description: "Drummer. Journaler. Music enthusiast. Collects cds. Chemical Engineer. Nailbiter. Likes whiskey."
baseurl: /
plugins:
  - "jekyll-paginate"
  - "jekyll-feed"
  - "jekyll-sitemap"
  - "jekyll-seo-tag"

author:
  name: "Tristan Lukens"
  url: https://tristanlukens.com

paginate: 5

include: ["_pages"]

name: tristan
