# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
# permalink: pretty
permalink: /:categories/:year/:title

# Setup
title: tristanlukens
description: "Drummer. Journaler. Muziekliefhebber. Cd-verzamelaar. Chemisch Technoloog. Nagelsbijter."
baseurl: ""
plugins:
  - "jekyll-paginate"
  - "jekyll-feed"
  - "jekyll-sitemap"
  - "jekyll-seo-tag"
  - "jekyll-date-localization"

author:
  name: "Tristan Lukens"
  url: https://tristanlukens.com

date_locale: nl

paginate: 5

include: ["_pages"]

name: tristan
