# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: tristanlukens
description: "Drummer. Journaler. Music enthusiast. Collects cds. Chemical Engineer. Nailbiter. Swears a lot."
baseurl: /
plugins:
  - "jekyll-paginate"

author:
  name: "Tristan Lukens"
  url: https://tristanlukens.com

paginate: 5

include: ["_pages"]

name: tristan
